version:  '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  nginx:
    image: nginx:1.21.4-alpine
    volumes:
      - './app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app/:/usr/src/app'
      - './docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}
